### ISSUE TITLE
Question 10 does not have a correct answer available.

### ISSUE THREAD

**Issue by iambryanhaney** [learn-co-curriculum/active-record-quiz#2]
`To write a migration to change a column name, which syntax is used?`

The answer given is

`change_column(table_name, column_name, type)`

But change_column will change the column's data-***type***.

**rename_column** is the correct method to change a column's name.

**Comment by maxwellbenton** [comment]
Hi @iambryanhaney,

Thank you for spotting this and providing feedback. We've updated the answer in question 10 to use the correct `rename_column` method, which should resolve this issue.

Thank you for contributing to a Learn lesson!
