### ISSUE TITLE
Typo in Question #10

### ISSUE THREAD

**Issue by afteralec** [learn-co-curriculum/active-record-quiz#3]
In the question:

10. To write a migration to change a column name, which syntax is used?

The correct answer is `rename_column(table_name, column_name, type)`

- And, in fact, all of the answers have 'type' as the final argument, but the correct syntax is actually:

`rename_column(table_name, column_name, new_column_name)` since we aren't changing type here at all.

**Comment by helloRupa** [comment]
Fixed in PR: https://github.com/learn-co-curriculum/active-record-quiz/pull/4/files
